package(
    default_visibility = ["//visibility:public"],
)

android_library(
    name = "lib",
    srcs = glob(["*.java"]),
    exports_manifest = 1,
    manifest = "AndroidManifest.xml",
    resource_files = glob(["res/**"]),
)
