load("@gmaven_rules//:defs.bzl", "gmaven_artifact")

android_binary(
    name = "hello_world",
    srcs = [],
    manifest = "AndroidManifest.xml",
    deps = [
        "@com_android_support_support_compat_28_0_0//aar",
    ],
)
